### ISSUE TITLE
Other Auth plugin examples? 

### ISSUE THREAD

**Issue by apatriz** [koopjs/koop-auth-direct-file#10]
I see that this plugin was tested with ArcGIS Online/Portal. 

I was wondering if anyone could provide insight on how to build an Auth plugin (this is the only Auth plugin example I could find) that works with Enterprise logins ? i.e. we have an ArcGIS site deployed in Azure, that uses [Azure AD identity provider](https://enterprise.arcgis.com/en/portal/latest/administer/windows/configure-azure-active-directory.htm) 

Any advice on how to modify this plugin or how I might get started rolling a custom Auth plugin that could work in this scenario ?

**Comment by hparkertt** [comment]
Have you found any solutions to this scenario?  I'm looking at solving a similar workflow.

**Comment by apatriz** [comment]
Never found a solution. We ended up just hosting the Koop server on an Azure App Service with built-in Azure AD authentication. Works in our case since we're only using the Koop endpoint from a custom web app. Still would like to revisit creating an Auth plugin for this scenario in the future
