### ISSUE TITLE
This auth provider does not seem to work with Koop 4

### ISSUE THREAD

**Issue by bveldkamp** [koopjs/koop-auth-direct-file#11]
koop-auth-direct-file references Koop ^3.7.2, so when using 4.x, this dependency won't resolve. 

I suppose this can be fixed by simply altering the version in [package.json](https://github.com/koopjs/koop-auth-direct-file/blob/master/package.json), but I don't know if the workings of an auth module have changed between 3.x and 4.x?

**Comment by rgwozdz** [comment]
Thanks for surfacing this. I actually think this is a misuse of peer-dependencies.  It should still work with latest Koop.  We can remove both peer dependencies from the package.json.  Would you care to PR?

**Comment by bveldkamp** [comment]
I'm away for a couple of weeks, so if you don't mind that, sure.
