### ISSUE TITLE
Authorization: type 'auth' is undefined

### ISSUE THREAD

**Issue by Joshuaweg** [koopjs/koop-auth-direct-file#5]
I am configuring a geoservices app and when I am adding the koop-auth-direct-file, i get this error

![image](https://user-images.githubusercontent.com/21377489/47744920-b0ad5500-dc3f-11e8-9fc2-3da66a5cfd3d.png)
here is the code from the start file

![image](https://user-images.githubusercontent.com/21377489/47744963-cd498d00-dc3f-11e8-9127-338a9f2260dc.png)

i do not understand what is wrong. I have the auth-direct-file installed on my project

**Comment by rgwozdz** [comment]
@Joshuaweg - what version of Koop are you using?  The auth-plugin type is only supported in Koop 3.7.2 and up.  I'd recommend using the latest version of Koop, v3.10.0.
