### ISSUE TITLE
Azure ArcGIS Portal Install not prompting to save credentials

### ISSUE THREAD

**Issue by keithfraley** [koopjs/koop-auth-direct-file#6]
We are running into problems with saving credentials from an azure arcgis portal install.  The user is prompted to enter credentials but the button to save the credentials is not presented.  Therefore the user cannot save the item with credentials.

The services are working fine on other machines.

**Comment by rgwozdz** [comment]
Hey @keithfraley - what version of portal are you working with?

**Comment by keithfraley** [comment]
10.6.1

**Comment by rgwozdz** [comment]
Any browser console errors, network errors, or node server errors?
