### ISSUE TITLE
How to control path to token service?

### ISSUE THREAD

**Issue by simon-fisher** [koopjs/koop-auth-direct-file#8]
I have successfully implemented the token auth provider with my own customization.  I can't seem to figure out how to control path to the token service?

In my output routes here is what I get;

"Geoservices" output routes for the "my-provider" provider     Methods
-------------------------------------------------------------  ---------
/my-provider/rest/info                                         GET, POST
/my-provider/tokens/:method                                    GET, POST
/my-provider/tokens/                                           GET, POST
/my-provider/:host/FeatureServer                               GET, POST
/my-provider/rest/services/:host/FeatureServer*                GET, POST
/my-provider/:host/FeatureServer*                              GET, POST
/my-provider/rest/services/:host/MapServer*                    GET, POST
/my-provider/:host/MapServer*                                  GET, POST

This ":host" above allows me to use any value ie. client1, client2 in here so I can control my own provider based on the host value.  I would like to do the same for the token service and have something like /my-provider/:host/tokens

Is this possible, and if so how? 

Thanks
Simon

**Comment by rgwozdz** [comment]
These routes are defined by the output plugin, so you're unable to change them here.  We would need to modify koop-output-geoservices to support.  Can you open an issue there?
