### ISSUE TITLE
Arcgis online is not prompting user name and password options

### ISSUE THREAD

**Issue by sjain227** [koopjs/koop-auth-direct-file#9]
When I tried to add a secure koop service in AGOL. It is not prompting user name and password fields. In developer tools, on network tab, it is stuck in token required:
({"error":{"code":499,"message":"Token Required","details":[]}})

I was expecting few more network calls after this which should take me to user name and password fields. But nothing happens after this and I get Service inaccessible error on the browser.

Also, When I add a non secure koop service, it works fine on AGOL.

Am I missing something?

**Comment by rgwozdz** [comment]
Can you paste in the URL of the service you are trying to add to AGOL?

**Comment by sjain227** [comment]
> Can you paste in the URL of the service you are trying to add to AGOL?

@rgwozdz I am using ES provider for fetching data and url is:  https://koopjs-h1.aws-us-east-1.dev-apps.sdu-rds.com/es/searchService/sdu_v2_well/FeatureServer

**Comment by rgwozdz** [comment]
Thanks you @sjain227.  I am wondering if you could update your deployment so that it uses the latest Koop (4.0.3).  We've updated the dependencies to handle non-integer authentication error code received from the Portal API.  This may be the cause of the issue.  Please let me know if this does or does not resolve the issue.

**Comment by sjain227** [comment]
@rgwozdz I updated koop to 4.0.3, Still same issue. 
Also, I have observed that If I remove ES provider and connect with file geojson directly something like  https://koopjs-h1.aws-us-east-1.dev-apps.sdu-rds.com/file-geojson/rest/services/line/FeatureServer (line.geojson available inside data folder) , It prompts for username and password.

**Comment by rgwozdz** [comment]
@sjain227 - thanks for checking.  Sounds like it is related to the ES provider then, thanks very much for that insight.  We are actually targeting the ES provider for refactor in the coming weeks, so we will target getting it to work with auth as well.

**Comment by sjain227** [comment]
@rgwozdz Thanks for your quick response, Even I was thinking the same but my doubt is when we remove auth completely then even ES service works. I am not sure how combination of Auth and ES stopping AGOL to prompt user name and password. This is my observation so far :

Secure ES service ---> Not able to publish in AGOL
Secure File Geojson ---> Working fine
Non secure ES service ----> Working fine
